PREFIX: "&x&F&F&8&3&F&7&lD&x&F&F&8&2&E&2&lu&x&F&F&8&0&C&D&le&x&F&F&7&F&B&9&ll&x&F&F&7&D&A&4&li&x&F&F&7&C&8&F&lt&x&F&F&7&A&7&A&ly &f&l»&r&f"

console:
  startup: "Duelity plugin started!"
  shutdown: "Duelity plugin disabled!"
  player: "You *MUST* be a player to run this command!"

settings:
  setup: false
  duel_server: true

player:
  y: "&aYes"
  n: "&cNo"
  permission: "&cYou do &lNOT &r&chave permission to run that command!"
  args: "&cMissing arguments!"
  "on": "&7[&a✔&7]"
  "off": "&7[&4❌&7]"

admin:
  setup_incomplete:
    - "&c------------------------------------"
    - "&fYour &lDuelity &r&fsetup is incomplete!"
    - "&fDo /#setup start to set up the plugin!"
    - "&c------------------------------------"

setup:
  name: "&aSetup Duelity"
  duel:
    name: "&aIs this a duel server?"
    lore:
      - "&fCurrently: ẞanswer"
  spawn:
    name: "&aSet spawn"
    close: "ßprefix Go to the spawn location, then type \"done\" in chat"
    action_bar: "Type \"done\" when you are done!"
    lore:
      - "&fClick here to set the spawn location"
  save:
    name: "&aComplete setup"
    done: "ẞprefix Config saved! Remember: You can always edit it using &6/#setup start &for via the &6config.yml &ffile!"
    lore:
      - "&fClick here to save the config!"

kits:
  name: "&aManage kits"
  add:
    name: "&aAdd kit"
    lore:
      - "&fClick here to add a kit!"
  no_kits:
    name: "&4There are no kits on the server!"
    lore:
      - "&cAdd a kit using the &f\"&aAdd a kit&f\" &citem."
  add_gui:
    name: "&aAdd a kit"
    set_name:
      name: "&aSet a name for your kit"
      gui:
        name: "&aSet kit name"
        exists: "&cA kit with this name already exists!"
        action_bar: "&aType the kit's name in chat!"
      lore:
        - "&fClick here to set a name for your kit"
      set_lore:
        - "&fCurrent name: ẞname"
    set_icon:
      name: "&aSet an icon for your kit"
      action_bar: "Hold the item and type \"done\"!"
      lore:
        - "&fClick here to set the icon of the kit"
    set_inventory:
      name: "&aSet the inventory"
      action_bar: "Prepare your inventory and type \"done\"!"
      lore:
        - "&fClick here to set the inventory"
    next:
      name: "&aSet kit attributes"
      health:
        name: "&aHP in your kit: &cẞhp"
        max: "ẞprefix Minimum HP is 1"
        lore:
          - "&a+ &fLeft click"
          - "&c- &fRight click"
          - "&4x10 &fShift click"
      gamemode:
        name: "&aSet Gamemode"
        lore:
          - "ẞa Survival"
          - "ẞb Adventure"
      map:
        name: "&aSelect maps"
        lore:
          - "&fClick here to set the maps this kit can be played on"
      arrow:
        name: "&aNext page"
        lore:
          - "&fClick here to go to the attributes page"
        skin: "ewogICJ0aW1lc3RhbXAiIDogMTc2NTgxNDEzNDU5NSwKICAicHJvZmlsZUlkIiA6ICI1MGM4NTEwYjVlYTA0ZDYwYmU5YTdkNTQyZDZjZDE1NiIsCiAgInByb2ZpbGVOYW1lIiA6ICJNSEZfQXJyb3dSaWdodCIsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9kMzRlZjA2Mzg1MzcyMjJiMjBmNDgwNjk0ZGFkYzBmODVmYmUwNzU5ZDU4MWFhN2ZjZGYyZTQzMTM5Mzc3MTU4IgogICAgfQogIH0KfQ"

arenas:
  name: "&aManage arenas"
  add:
    name: "&aAdd arena"
    lore:
      - "&fClick here to add an arena!"
  arena:
    color: "&6"
    lore:
      - "&fRight click to manage"
  no_arenas:
    name: "&4There are no arenas on the server!"
    lore:
      - "&cAdd an arena using the &f\"&aAdd arena&f\" &citem."
  world:
    check:
      - "ẞmap &fMap"
      - "ẞblue &fBlue spawn"
      - "ẞred &fRed spawn"
    save: "ẞprefix Map saved!"
    set_name: "ẞprefix Set the name!"
    name_exists: "ẞprefix A map with this name already exists!"
    no_icon: "ẞprefix To set the arena's icon, please hold the item in your hand and drop it!"
    join: "ẞprefix You are in the arena editor! Type /#arenas save <name> to save, /leave to leave!"
    quit: "ẞprefix You left the arena editor!"
    blue_saved: "ẞprefix Blue spawn has been saved!"
    red_saved: "ẞprefix Red spawn has been saved!"
    too_many: "ẞprefix Too many arenas!"
  wand:
    name: "&7Area wand"
    primary:
      - "&7[&a✔&7] Primary location selected!"
      - "&7(X ẞx Y ẞy Z ẞz)"
    secondary:
      - "&7[&a✔&7] Secondary location selected!"
      - "&7(X ẞx Y ẞy Z ẞz)"
    lore:
      - "&aLeft click for Primary selection"
      - "&cRight click for Secondary selection"
  edit:
    name: "&aEdit ẞname"
    delete:
      name: "&cDelete arena"
      lore:
        - "&cThis step cannot be reversed!"
      deleted: "ẞprefix Arena deleted!"
      failed_to_delete: "ẞprefix Failed to delete arena!"
    edit_name:
      name: "&aEdit name"
      exists: "ẞprefix An arena with this name already exists!"
      lore:
        - "&fClick here to edit the arena's name"
      action_bar: "Type the Arena's name in the chat!"
    back:
      name: "&7Back"
    icon:
      name: "&aEdit icon"
      lore:
        - "&fClick here to set the icon"
      action_bar: "Hold the item and type \"done\"!"