PREFIX: "&x&F&F&8&3&F&7&lD&x&F&F&8&2&E&2&lu&x&F&F&8&0&C&D&le&x&F&F&7&F&B&9&ll&x&F&F&7&D&A&4&li&x&F&F&7&C&8&F&lt&x&F&F&7&A&7&A&ly &f&l¬ª&r&f"

console:
  startup: "Duelity plugin started!"
  shutdown: "Duelity plugin disabled!"
  player: "You *MUST* be a player to run this command!"

settings:
  duel_server: true
  difficulty: "HARD"
  skip: true

player:
  y: "&aYes"
  n: "&cNo"
  permission: "&cYou do &lNOT &r&chave permission to run that command!"
  args: "&cMissing arguments!"
  "on": "&7[&a‚úî&7]"
  "off": "&7[&4‚ùå&7]"

admin:
  kit_editor_alert: "&e&lWARNING: &r&cPlayer &4%player% &ctried to put an illegal item into a kit!"

settings_menu:
  name: "&aDuelity Settings"
  duel:
    name: "&aIs this a duel server?"
    lore:
      - "&fCurrently: ·∫ûanswer"
  spawn:
    name: "&aSet spawn"
    close: "·∫ûprefix Go to the spawn location, then type \"done\" in chat"
    action_bar: "Type \"done\" when you are done!"
    lore:
      - "&fClick here to set the spawn location"
  difficulty:
    name: "&aSelect Duel difficulty"
  difficulties:
    - "·∫ûa Easy"
    - "·∫ûb Normal"
    - "·∫ûc Hard"
  skip:
    name: "&aPlayers can skip duels"
    lore:
      - "&fCurrently: ·∫ûanswer"

kits:
  name: "&aManage kits"
  saved: "·∫ûprefix Kit successfully saved!"
  too_many: "·∫ûprefix There are too many kits!"
  kit:
    color: "&6"
    lore:
      - "&fRight click to edit"
      - "&fLeft click to claim"
  add:
    name: "&aAdd kit"
    lore:
      - "&fClick here to add a kit!"
  no_kits:
    name: "&4There are no kits on the server!"
    lore:
      - "&cAdd a kit using the &f\"&aAdd a kit&f\" &citem."
  add_gui:
    name: "&aAdd a kit"
    set_name:
      name: "&aSet a name for your kit"
      gui:
        name: "&aSet kit name"
        exists: "&cA kit with this name already exists!"
        action_bar: "&aType the kit's name in chat!"
      lore:
        - "&fClick here to set a name for your kit"
      set_lore:
        - "&fCurrent name: ·∫ûname"
    set_icon:
      name: "&aSet an icon for your kit"
      action_bar: "Hold the item and type \"done\"!"
      lore:
        - "&fClick here to set the icon of the kit"
    set_inventory:
      name: "&aSet the inventory"
      action_bar: "Prepare your inventory and type \"done\"!"
      lore:
        - "&fClick here to set the inventory"
    health:
      name: "&aHP in your kit: &c·∫ûhp"
      max: "·∫ûprefix Minimum HP is 1"
      lore:
        - "&a+ &fLeft click"
        - "&c- &fRight click"
        - "&4x10 &fShift click"
    gamemode:
      name: "&aSet Gamemode"
      lore:
        - "·∫ûa Survival"
        - "·∫ûb Adventure"
    regen:
      name: "&aNatural regeneration"
      lore:
        - "&fNatural regeneration: ·∫ûanswer"
    map:
      name: "&aSelect maps"
      lore:
        - "&fClick here to set the maps this kit can be played on"
    arrow:
      name: "&aNext page"
      lore:
        - "&fClick here to go to the attributes page"
      skin: "ewogICJ0aW1lc3RhbXAiIDogMTc2NTgxNDEzNDU5NSwKICAicHJvZmlsZUlkIiA6ICI1MGM4NTEwYjVlYTA0ZDYwYmU5YTdkNTQyZDZjZDE1NiIsCiAgInByb2ZpbGVOYW1lIiA6ICJNSEZfQXJyb3dSaWdodCIsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9kMzRlZjA2Mzg1MzcyMjJiMjBmNDgwNjk0ZGFkYzBmODVmYmUwNzU5ZDU4MWFhN2ZjZGYyZTQzMTM5Mzc3MTU4IgogICAgfQogIH0KfQ"
  save:
    name: "&aSave kit"
    lore:
      - "&fClick here to save the kit!"
    skin: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDk5ODBjMWQyMTE4MDlhOWI2NTY1MDg4ZjU2YTM4ZjJlZjQ5MTE1YzEwNTRmYTY2MjQ1MTIyZTllZWVkZWNjMiJ9fX0="

arenas:
  name: "&aManage arenas"
  invalid_name: "·∫ûprefix Your arena's name may only contain english letters, numbers and these characters: \":\", \"-\", \"_\"."
  add:
    name: "&aAdd arena"
    lore:
      - "&fClick here to add an arena!"
  arena:
    color: "&6"
    lore:
      - "&fRight click to manage"
  no_arenas:
    name: "&4There are no arenas on the server!"
    lore:
      - "&cAdd an arena using the &f\"&aAdd arena&f\" &citem."
  world:
    check:
      - "·∫ûmap &fMap"
      - "·∫ûblue &fBlue spawn"
      - "·∫ûred &fRed spawn"
    save: "·∫ûprefix Map saved!"
    set_name: "·∫ûprefix Set the name!"
    name_exists: "·∫ûprefix A map with this name already exists!"
    no_icon: "·∫ûprefix To set the arena's icon, please hold the item in your hand and drop it!"
    join: "·∫ûprefix You are in the arena editor! Type /#arenas save <name> to save, /leave to leave!"
    quit: "·∫ûprefix You left the arena editor!"
    blue_saved: "·∫ûprefix Blue spawn has been saved!"
    red_saved: "·∫ûprefix Red spawn has been saved!"
    too_many: "·∫ûprefix Too many arenas!"
  wand:
    name: "&7Area wand"
    primary:
      - "&7[&a‚úî&7] Primary location selected!"
      - "&7(X ·∫ûx Y ·∫ûy Z ·∫ûz)"
    secondary:
      - "&7[&a‚úî&7] Secondary location selected!"
      - "&7(X ·∫ûx Y ·∫ûy Z ·∫ûz)"
    lore:
      - "&aLeft click for Primary selection"
      - "&cRight click for Secondary selection"
  edit:
    name: "&aEdit ·∫ûname"
    delete:
      name: "&cDelete arena"
      lore:
        - "&cThis step cannot be reversed!"
      deleted: "·∫ûprefix Arena deleted!"
      failed_to_delete: "·∫ûprefix Failed to delete arena!"
    edit_name:
      name: "&aEdit name"
      exists: "·∫ûprefix An arena with this name already exists!"
      lore:
        - "&fClick here to edit the arena's name"
      action_bar: "Type the Arena's name in the chat!"
    back:
      name: "&7Back"
    icon:
      name: "&aEdit icon"
      lore:
        - "&fClick here to set the icon"
      action_bar: "Hold the item and type \"done\"!"

editor:
  name: "&aKit editor"
  saved: "&aKit saved!"
  warning: "&eIllegal items found!"
  reset: "&aKit reset!"
  admin:
    import: "&7Import"
    delete: "&cDelete"
    back: "&7Back"
    options: "&7Options"
  player:
    save: "&aSave"
    reset: "&6Reset"
  edit:
    edit_name:
      name: "&aEdit kit name"
      lore:
        - "&fClick here to edit the kit's name"
    edit_icon:
      name: "&aEdit kit icon"
      lore:
        - "&fClick here to edit the kit's icon"
    delete:
      name: "&cDelete kit"
      deleted: "·∫ûprefix Kit selected successfully!"
      lore:
        - "&cThis step cannot be reversed!"
    health:
      name: "&aHealth in your kit: &c·∫ûhp"
      max: "·∫ûprefix Minimum HP is 1"
      lore:
        - "&a+ &fLeft click"
        - "&c- &fRight click"
        - "&4x10 &fShift click"
    gamemode:
      name: "&aSet Gamemode"
      lore:
        - "·∫ûa Survival"
        - "·∫ûb Adventure"
    map:
      name: "&aSelect maps"
      lore:
        - "&fClick here to set the maps this kit can be played on"

duel:
  name: "&aDuel: &3%player%"
  offline: "&7%player% is not online!"
  self: "&7You can't invite yourself!"
  color: "&9"
  sent: "&7You have already sent a duel request to that player!"
  no_sent_invite: "&7You haven't invited this player yet!"
  request_cancelled: "&7Your duel request has been cancelled for %player%!"
  no_invite: "&7You don't have a duel request by %player%!"
  declined: "&7You have declined your duel request from %player%!"
  in_duel: "&7%player% is already in a duel!"
  skip: "&7(&fSneak to skip: ·∫ûstatus&7)"
  skipped: "·∫ûplayer &fis ready to fight!"
  left:
    title: "&e%player% left!"
    subtitle: "&6Returning you to the lobby..."
  left_player:
    title: "&eYou left!"
    subtitle: "&6Returning you to the lobby..."
  countdown:
    title: "&e%time%"
    subtitle: "&9%blue_score% &7| &c%red_score% &7(first to %rounds%)"
  end:
    title: "&cDuel has ended!"
    subtitle: "&e%player% &6won"
  duel_start:
    title: " "
    subtitle: "&eGood luck!"
  no_kits:
    name: "&4There are no kits on the server!"
    lore:
      - "&cCreate one using /#kits!"
  round_message:
    - "&8&l----------------------------------------"
    - "&7(&9%blue_score% &8- &c%red_score%&7) &8%player% &7won the duel!"
    - "&c‚ù§ %player_health%/%max_health%"
    - "&8&l----------------------------------------"
  sender:
    expired: "&7Your duel request to %player% has expired!"
  receiver:
    expired: "&7Your duel request from %player% has expired!"
  duel_timeout: 120
  accepted: "&eDuel accepted!"
  gui:
    spectate:
      name: "&eEnable spectators: %state%"
      lore:
        - "&fBy turning this on, you allow"
        - "&f&leveryone &fto watch your duels"
    rounds:
      name: "&eRounds: &7%rounds%"
      lore:
        - "&fThe rounds someone has to win"
        - "&fto end the duel."
  message:
    receiver:
      - "<gradient:#8F8F8F:#D4D4D4><bold>=================================================</gradient>"
      - "<white><player> <grey>has sent you a duel request!"
      - "<accept> <decline> <information>"
      - "<gradient:#8F8F8F:#D4D4D4><bold>=================================================</gradient>"
    sender:
      - "<gold>Your duel request has been sent! <cancel>"
    accept:
      text: "&7[&a‚úî Accept&7]"
      hover: "&aClick here to accept the the duel request!"
    decline:
      text: "&7[&4‚ùå&7]"
      hover: "&cClick here to decline the duel request!"
    cancel:
      text: "&7[&4‚ùå&7]"
      hover: "&cClick here to cancel the duel request!"
    information:
      text: "&e[üìò]"
      hover:
        - "&7‚öú &9·¥è·¥ò·¥ò·¥è…¥·¥á…¥·¥õ: ·∫ûopponent"
        - "&7‚ìò &b·¥ã…™·¥õ: ·∫ûkit"
        - "&7‚Ñπ &e“ì…™ Äs·¥õ ·¥õ·¥è: ·∫ûrounds"
        - "&7‚ò¢ &ds·¥ò·¥á·¥Ñ·¥õ·¥Ä·¥õ·¥è Äs: ·∫ûspectators"

spectate:
  offline: "&7%player% is not online!"
  self: "&7You cannot spectate yourself!"
  not_in_duel: "&7%player% is not in duel!"
  disabled: "&7%player% disabled spectators"
  in_spectator: "&7%player% is in spectator!"